exports.articles = [
  {
    _id: 'bugs-bright-clothes',
    id: 'bugs-bright-clothes',
    title: 'Bugs Love Your Bright Clothes',
    wordCount: 252,
    level: 'CET-6',
    visualSymbol: 'Y',
    visualCaption: 'Color cues and insect vision',
    content:
      'Recently, try to avoid wearing yellow when you go out — otherwise, you might find yourself strangely more attractive, but only to insects.\n\nUnlike older parts of plants, young leaves and flowers tend to be brighter, with many flowers being yellow in color to attract pollinators. For pollinating insects, bright yellow means a feast of nectar and pollen.\n\nInsects have compound eyes and are sensitive to ultraviolet light, but they also see bright colors such as yellow and blue much better than humans do. That is why yellow clothes can look like a beacon to bugs.\n\nSo the next time you plan a picnic or a walk in the park, perhaps skip the yellow shirt — unless you want to become the most popular person at the insect party.',
    source: 'Annie Daily',
    theme: {
      accent: '#80C934',
      warm: '#FFD64A',
      cool: '#38B7C9',
      paper: '#FFF8E8',
      shadow: 'rgba(116, 82, 20, 0.16)',
      warmSoft: 'rgba(255, 214, 74, 0.42)',
      coolSoft: 'rgba(56, 183, 201, 0.30)',
      visualStart: 'rgba(255, 245, 205, 0.92)',
      visualEnd: 'rgba(225, 249, 247, 0.78)',
      accentSoft: 'rgba(128, 201, 52, 0.14)',
    },
    tags: ['science', 'cet-6'],
    sortOrder: 10,
    status: 'published',
    createdAt: 1782921600000,
    updatedAt: 1782921600000,
    publishedAt: 1782921600000,
  },
  {
    _id: 'walking',
    id: 'walking',
    title: 'The Quiet Power of Walking',
    wordCount: 285,
    level: 'CET-4',
    visualSymbol: 'W',
    visualCaption: 'Nature, rhythm, and attention',
    content:
      'For most of human history, walking was simply how we got from one place to another. But modern science is revealing something remarkable. Walking, especially in nature, has profound effects on the human brain.\n\nA landmark study from Stanford University found that people who walked for ninety minutes through a natural setting showed significantly lower activity in the part of the brain associated with repetitive negative thoughts.\n\nWalking also boosts creativity. In a series of experiments, researchers discovered that people generated nearly twice as many creative ideas while walking compared to sitting.',
    source: 'Stanford Medicine',
    theme: {
      accent: '#3A9B72',
      warm: '#DDEEC7',
      cool: '#6CB8A8',
      paper: '#F4FAF4',
      shadow: 'rgba(37, 105, 76, 0.14)',
      warmSoft: 'rgba(221, 238, 199, 0.46)',
      coolSoft: 'rgba(108, 184, 168, 0.30)',
      visualStart: 'rgba(241, 250, 235, 0.92)',
      visualEnd: 'rgba(224, 245, 240, 0.78)',
      accentSoft: 'rgba(58, 155, 114, 0.14)',
    },
    tags: ['health', 'cet-4'],
    sortOrder: 20,
    status: 'published',
    createdAt: 1782921600000,
    updatedAt: 1782921600000,
    publishedAt: 1782921600000,
  },
  {
    _id: 'dreams',
    id: 'dreams',
    title: 'Why Some People Remember Their Dreams',
    wordCount: 262,
    level: 'CET-6',
    visualSymbol: 'D',
    visualCaption: 'Sleep, memory, and recall',
    content:
      'Every morning, millions of people wake up with vivid memories of strange and wonderful dreams. Others open their eyes and recall nothing at all.\n\nNeuroscientists have been studying this question for decades. The answer appears to lie not in how much people dream, but in how easily their brains wake up during the night.\n\nIf you want to remember more of your dreams, keep a dream journal by your bed.',
    source: 'Nature Neuroscience',
    theme: {
      accent: '#6E7BEF',
      warm: '#EBD7FF',
      cool: '#9DB4FF',
      paper: '#F6F4FF',
      shadow: 'rgba(79, 74, 155, 0.16)',
      warmSoft: 'rgba(235, 215, 255, 0.44)',
      coolSoft: 'rgba(157, 180, 255, 0.32)',
      visualStart: 'rgba(246, 238, 255, 0.92)',
      visualEnd: 'rgba(231, 236, 255, 0.78)',
      accentSoft: 'rgba(110, 123, 239, 0.14)',
    },
    tags: ['sleep', 'cet-6'],
    sortOrder: 30,
    status: 'published',
    createdAt: 1782921600000,
    updatedAt: 1782921600000,
    publishedAt: 1782921600000,
  },
]

exports.articleLearningContent = [
  {
    _id: 'bugs-bright-clothes',
    articleId: 'bugs-bright-clothes',
    status: 'ready',
    provider: 'local-prebuilt',
    model: 'local-prebuilt',
    updatedAt: '2026-06-23',
    generatedAt: 1782921600000,
    sentenceTranslations: {
      '0:0': {
        text: 'Recently, try to avoid wearing yellow when you go out — otherwise, you might find yourself strangely more attractive, but only to insects.',
        translation: '最近，外出时尽量避免穿黄色，否则你可能会发现自己莫名其妙地更有吸引力，只不过吸引的是昆虫。',
        note: 'otherwise 表示“否则”；but only to insects 是转折补充，带一点幽默感。',
      },
      '1:0': {
        text: 'Unlike older parts of plants, young leaves and flowers tend to be brighter, with many flowers being yellow in color to attract pollinators.',
        translation: '和植物较老的部分不同，嫩叶和花朵通常颜色更鲜亮，许多花呈黄色，是为了吸引传粉昆虫。',
        note: 'Unlike 放在句首引出对比；with many flowers being... 是伴随说明。',
      },
      '1:1': {
        text: 'For pollinating insects, bright yellow means a feast of nectar and pollen.',
        translation: '对传粉昆虫来说，明亮的黄色意味着一场花蜜和花粉的盛宴。',
        note: 'a feast of 不只表示宴会，也可比喻“大量、丰富的东西”。',
      },
      '2:0': {
        text: 'Insects have compound eyes and are sensitive to ultraviolet light, but they also see bright colors such as yellow and blue much better than humans do.',
        translation: '昆虫有复眼，对紫外线很敏感，同时它们识别黄色、蓝色等亮色的能力也比人类强得多。',
        note: 'be sensitive to 表示“对……敏感”；much better than humans do 中 do 代替前面的 see。',
      },
      '2:1': {
        text: 'That is why yellow clothes can look like a beacon to bugs.',
        translation: '这就是为什么黄色衣服在虫子眼里会像一座醒目的信号灯。',
        note: 'That is why... 用来解释原因；beacon 是“灯塔、信号灯”的比喻。',
      },
      '3:0': {
        text: 'So the next time you plan a picnic or a walk in the park, perhaps skip the yellow shirt — unless you want to become the most popular person at the insect party.',
        translation: '所以下次你计划去野餐或在公园散步时，也许该跳过那件黄色衬衫，除非你想成为昆虫派对上最受欢迎的人。',
        note: 'the next time 可直接引导时间状语；skip 在这里是“略过、不选”。',
      },
    },
    wordExplanations: {
      avoid: {
        word: 'avoid',
        phonetic: '/əˈvɔɪd/',
        partOfSpeech: 'v.',
        meaning: '避免；避开',
        example: 'Try to avoid wearing yellow when you go out.',
        exampleTranslation: '外出时尽量避免穿黄色。',
        note: '常接名词或动名词：avoid doing sth.',
      },
      pollinators: {
        word: 'pollinator',
        phonetic: '/ˈpɑːləneɪtər/',
        partOfSpeech: 'n.',
        meaning: '传粉者；传粉昆虫',
        example: 'Many flowers use color to attract pollinators.',
        exampleTranslation: '许多花通过颜色吸引传粉昆虫。',
      },
      compound: {
        word: 'compound',
        phonetic: '/ˈkɑːmpaʊnd/',
        partOfSpeech: 'adj.',
        meaning: '复合的；组合的',
        example: 'Insects have compound eyes.',
        exampleTranslation: '昆虫有复眼。',
      },
      ultraviolet: {
        word: 'ultraviolet',
        phonetic: '/ˌʌltrəˈvaɪələt/',
        partOfSpeech: 'adj.',
        meaning: '紫外线的',
        example: 'Ultraviolet light is invisible to humans.',
        exampleTranslation: '紫外线对人类来说是不可见的。',
      },
      beacon: {
        word: 'beacon',
        phonetic: '/ˈbiːkən/',
        partOfSpeech: 'n.',
        meaning: '灯塔；信号灯；醒目标志',
        example: 'The yellow shirt looked like a beacon to bugs.',
        exampleTranslation: '那件黄色衬衫在虫子眼里像一个醒目的信号灯。',
      },
      skip: {
        word: 'skip',
        phonetic: '/skɪp/',
        partOfSpeech: 'v.',
        meaning: '跳过；略过；不选',
        example: 'Perhaps skip the yellow shirt.',
        exampleTranslation: '也许该跳过那件黄色衬衫。',
      },
    },
    reviewedPhrases: [
      { text: 'compound eyes', meaning: '复眼', reason: 'CET-6 科普语境常见表达' },
      { text: 'ultraviolet light', meaning: '紫外线', reason: '科普文章高频术语' },
      { text: 'look like a beacon', meaning: '像醒目的信号灯', reason: '比喻表达，适合精读' },
      { text: 'skip the yellow shirt', meaning: '别选那件黄色衬衫', reason: 'skip 的口语动词用法' },
    ],
  },
  {
    _id: 'walking',
    articleId: 'walking',
    status: 'ready',
    provider: 'local-prebuilt',
    model: 'local-prebuilt',
    updatedAt: '2026-06-23',
    generatedAt: 1782921600000,
    sentenceTranslations: {
      '0:0': {
        text: 'For most of human history, walking was simply how we got from one place to another.',
        translation: '在人类历史的大部分时间里，步行只是我们从一个地方到另一个地方的方式。',
        note: 'how we got... 是表语从句，解释 walking was simply 什么。',
      },
      '0:1': {
        text: 'But modern science is revealing something remarkable.',
        translation: '但现代科学正在揭示一些不同寻常的发现。',
        note: 'remarkable 表示“值得注意的、非凡的”，比 interesting 更正式。',
      },
      '0:2': {
        text: 'Walking, especially in nature, has profound effects on the human brain.',
        translation: '步行，尤其是在自然环境中步行，会对人脑产生深远影响。',
        note: 'especially in nature 是插入补充；profound effects 是学术写作常用搭配。',
      },
      '1:0': {
        text: 'A landmark study from Stanford University found that people who walked for ninety minutes through a natural setting showed significantly lower activity in the part of the brain associated with repetitive negative thoughts.',
        translation: '斯坦福大学一项具有里程碑意义的研究发现，在自然环境中步行九十分钟的人，大脑中与反复负面想法相关的区域活动明显降低。',
        note: '主干是 A study found that...；who walked... 修饰 people，associated with... 修饰 part of the brain。',
      },
      '1:1': {
        text: 'Unlike older parts of plants, young leaves and flowers tend to be brighter, with many flowers being yellow in color to attract pollinators.',
        translation: '和植物较老的部分不同，嫩叶和花朵通常更鲜亮，许多花呈黄色，是为了吸引传粉昆虫。',
        note: 'Unlike 引出对比；with many flowers being... 是伴随说明结构。',
      },
      '2:0': {
        text: 'Walking also boosts creativity.',
        translation: '步行还会提升创造力。',
        note: 'boost 表示“提升、促进”，常用于能力、经济、信心等抽象名词。',
      },
      '2:1': {
        text: 'In a series of experiments, researchers discovered that people generated nearly twice as many creative ideas while walking compared to sitting.',
        translation: '在一系列实验中，研究人员发现，与坐着相比，人们在步行时产生的创意想法几乎多了一倍。',
        note: 'twice as many... compared to... 是倍数比较结构。',
      },
    },
    wordExplanations: {
      profound: {
        word: 'profound',
        phonetic: '/prəˈfaʊnd/',
        partOfSpeech: 'adj.',
        meaning: '深远的；重大的',
        example: 'Walking has profound effects on the brain.',
        exampleTranslation: '步行会对大脑产生深远影响。',
      },
      repetitive: {
        word: 'repetitive',
        phonetic: '/rɪˈpetətɪv/',
        partOfSpeech: 'adj.',
        meaning: '重复的；反复的',
        example: 'The study focused on repetitive negative thoughts.',
        exampleTranslation: '这项研究关注反复出现的负面想法。',
      },
      boosts: {
        word: 'boost',
        phonetic: '/buːst/',
        partOfSpeech: 'v.',
        meaning: '提高；促进',
        example: 'Walking boosts creativity.',
        exampleTranslation: '步行能提升创造力。',
      },
    },
    reviewedPhrases: [
      { text: 'profound effects', meaning: '深远影响', reason: '学术写作高频搭配' },
      { text: 'repetitive negative thoughts', meaning: '反复出现的负面想法', reason: '心理学语境重点短语' },
      { text: 'boosts creativity', meaning: '提升创造力', reason: 'boost + 抽象名词的常见用法' },
    ],
  },
  {
    _id: 'dreams',
    articleId: 'dreams',
    status: 'ready',
    provider: 'local-prebuilt',
    model: 'local-prebuilt',
    updatedAt: '2026-06-23',
    generatedAt: 1782921600000,
    sentenceTranslations: {
      '0:0': {
        text: 'Every morning, millions of people wake up with vivid memories of strange and wonderful dreams.',
        translation: '每天早晨，数百万人醒来时都清楚记得那些奇异而美妙的梦。',
        note: 'wake up with... 表示“醒来时带着/拥有某种状态或记忆”。',
      },
      '0:1': {
        text: 'Others open their eyes and recall nothing at all.',
        translation: '另一些人睁开眼，却什么也回想不起来。',
        note: 'nothing at all 强调“完全没有”。',
      },
      '1:0': {
        text: 'Neuroscientists have been studying this question for decades.',
        translation: '神经科学家已经研究这个问题几十年了。',
        note: 'have been studying 是现在完成进行时，强调动作持续到现在。',
      },
      '1:1': {
        text: 'The answer appears to lie not in how much people dream, but in how easily their brains wake up during the night.',
        translation: '答案似乎不在于人们做了多少梦，而在于他们的大脑夜间多容易醒来。',
        note: 'not in..., but in... 是“不在于……而在于……”的平衡结构。',
      },
      '2:0': {
        text: 'If you want to remember more of your dreams, keep a dream journal by your bed.',
        translation: '如果你想记住更多梦境，可以在床边放一本梦境日记。',
        note: 'keep... by your bed 表示“把……放在床边”。',
      },
    },
    wordExplanations: {
      vivid: {
        word: 'vivid',
        phonetic: '/ˈvɪvɪd/',
        partOfSpeech: 'adj.',
        meaning: '清晰的；生动的',
        example: 'She woke up with vivid memories of a dream.',
        exampleTranslation: '她醒来时清楚记得一个梦。',
      },
      recall: {
        word: 'recall',
        phonetic: '/rɪˈkɔːl/',
        partOfSpeech: 'v.',
        meaning: '回想起；记起',
        example: 'Others recall nothing at all.',
        exampleTranslation: '另一些人什么也回想不起来。',
      },
      journal: {
        word: 'journal',
        phonetic: '/ˈdʒɜːrnl/',
        partOfSpeech: 'n.',
        meaning: '日记；日志；期刊',
        example: 'Keep a dream journal by your bed.',
        exampleTranslation: '在床边放一本梦境日记。',
      },
    },
    reviewedPhrases: [
      { text: 'vivid memories', meaning: '清晰的记忆', reason: '描述记忆/梦境的高频搭配' },
      { text: 'recall nothing at all', meaning: '完全想不起来', reason: 'nothing at all 的强调用法' },
      { text: 'wake up during the night', meaning: '夜间醒来', reason: '睡眠研究语境重点表达' },
      { text: 'dream journal', meaning: '梦境日记', reason: '主题核心词组' },
    ],
  },
]
